sources:
  - name: graph-activity-feed
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-activity-arbitrum-goerli
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 10
  - name: graph-network-subgraph
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-arbitrum-goerli
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 10


documents:
  - src/queries/openAllocation.graphql
  - src/queries/closeAllocation.graphql
